### ISSUE TITLE
Docs can't build without PyMCNP installed

### ISSUE THREAD

**Issue by MicahGale** [FSIBT/PyMCNP#2]
I tried to build the docs to learn more from a fresh clone (prior to pip install). I got:

``` 
>make html
Running Sphinx v7.4.7
loading translations [en]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 8 source files that are out of date
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... [100%] pymcnp-utils
WARNING: autodoc: failed to import class 'cli.Ls' from module 'pymcnp'; the following exception was raised:
No module named 'pymcnp'
...
```

I think this means that sphinx is using the installed version of `PyMCNP` instead of the local version to build the documentation, which could lead to stale documentation. A relative import should be used instead. 

you may want to add something like the following in `doc/source/conf.py`

``` python
sys.path.insert(0, os.path.abspath("../.."))
import pymcnp
```

**Comment by BitterB0NG0** [comment]
Thank you for your suggestion! You can also find the docs online: [ReadTheDocs](https://pymcnp.readthedocs.io/en/latest/?badge=latest).

**Comment by MicahGale** [comment]
That would be a great link to add to the description/about section of the repo (the right side of the home page).
