### ISSUE TITLE
Make this package more discoverable

### ISSUE THREAD

**Issue by MicahGale** [FSIBT/PyMCNP#5]
I don't know how widely you are pushing this yet, since I only found this by seeing a pre-conference abstract from IEEE, but here are some suggestions:

1. Add the [MCNP](https://github.com/topics/mcnp) topic to the repo ([guide](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics)).
2. Deploy to [PyPI](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/). Is this in the plans long term? It would be a lot easier to install than having every user `git clone`.

**Comment by arunpersaud** [comment]
Hi, thanks for you comments. We plan to do a 0.1 release on PyPI in the next days ;) Currently still early days and we are also recently started a complete rewrite, so some features we had are not working right now...  I'll check out how to add the topic now.

**Comment by arunpersaud** [comment]
It's now on pypi:
https://pypi.org/project/pymcnp/0.1.2/
